### PR TITLE
Cancel editing in getstring() on window resize

### PR DESCRIPTION
**Pull request by lhca**
Adresses #145. It seems a reasonable compromise that the edit is aborted.

### CODE REVIEW

**Comment by lfos** [comment]
I am not convinced that aborting is a better idea than having the panels not updated for a while... While the latter is not esthetically pleasing, the former means that data is potentially lost.

**Comment by lhca** [comment]
The input generated by a resize should be taken care of in any case. Another possibility is to handle `KEY_RESIZE` like `ERR` and ignore it (i.e. `continue;`) and hope that the messed-up screen allows the editing to continue.

**Comment by lfos** [comment]
True. I'd prefer the option to ignore the input as a workaround; maybe with a "FIXME" comment that mentions that resize should be handled properly at some point. Thanks!

**Comment by lfos** [comment]
Pushed an alternative workaround, thanks for the idea!

**Pull request closed without merging**
