### PR TITLE
Fix compile issues in doc directory

### PR DESCRIPTION
**Pull request by bmunger**
This solves issue with the Makefile in the doc directory.  Some files have been renamed or converted and not reflected in the m4 file.

### CODE REVIEW

**Comment by lfos** [comment]
Thank you for opening this PR. I think you are addressing a long-standing issue.

Unfortunately, it is not that simple, though: currently, the release tarballs include pre-built documentation and *should* allow for performing a full build (including documentation) without having AsciiDoc installed. If it does not, please let me know. When using a development snapshot, AsciiDoc is a requirement for building documentation.

Therefore, the build system currently checks for AsciiDoc but only warns when it is not available (since a build running from a release tarball will complete successfully anyways). I see two options:

1. Add an additional check to the `configure` and error out if neither AsciiDoc nor pre-built documentation is available.
2. Make AsciiDoc a requirement, even for release tarballs.

I prefer the first option. Opinions?

**Comment by vxid** [comment]
I think the first option is preferable as well.

**Comment by bmunger** [comment]
Option 1 should be fine.  configure should not complete without error in a condition where make will fail.

**Comment by lfos** [comment]
Are you interested in replacing this PR with a patch that implements this?

**Comment by bmunger** [comment]
Sure no problem.  Soon as I get home from work I will revert and add the conditional checks to configure.ac.  Thanks.

**Comment by bmunger** [comment]
Reverted previous change.  This change to configure.ac will warn when asciidoc and a2x have not been found but will continue if pre-built documentation and man pages are found, if not it will produce an error.  I don't expect that the a2x error will ever be seen since it's part of the asciidoc package though.  I opted to use shell functions to test for the pre-built files instead of AC_CHECK_FILE due to some concerns over cross compile during package building which may happen in some Linux distributions.  The changes have been tested without asciidoc and without the pre-built files, without asciidoc and with pre-built files, and with asciidoc.  It behaves as expected.  Let me know if this is acceptable.  Thanks.

**Comment by lfos** [comment]
Merged into pu with some minor changes. Thanks!

**Pull request closed without merging**
