### PR TITLE
Export note to .ical files

### PR DESCRIPTION
**Pull request by DavidSpenler**
I've modified the export feature for the ical format by allowing notes in calcurse to be included in the file under the property 'DESCRIPTION' in accordance with the icalendar standard. This is logical because the 'DESCRIPTION' feature is currently unused and is roughly analogous to the note feature in calcurse.

To accomplish this, I added the function `read_note_content` to `note.c`, as well as its prototype to `calcurse.h`, which extracts the note content using the filename stored in the respective struct. This function is called in `ical.c`  from functions `ical_export_apoints`, `ical_export_recur_apoints`, `ical_export_events`, `ical_export_recur_events`, and `ical_export_todo`, after checking if the provided struct's `note` member is not null. It then outputs the note like normal.

### CODE REVIEW

**Comment by DavidSpenler** [comment]
Thanks for the reply.

ical_format_newlines() is not in this branch, I've moved only the note export-related code from the branch in my old PR. Please let me know if I've done this incorrectly, as this project is my first attempt at making contributions on github.

Also, as it turns out, google calendar now accepts .ical files with CRLF, and LF newline sequences. As such, until someone reports bugs related to newline pickiness from other applications, I see no reason to bloat the code with that component, and I will not be making a pull request for it.

**Comment by lfos** [comment]
Well, you introduce that function in commit 504998e and remove it again in 4d8baf9. You can view the commits yourself, they are listed below the initial PR message. I think you may want to reogranize them...

**Comment by lfos** [comment]
Any news?

**Comment by lfos** [comment]
We plan on preparing a release soon, so if we want to have this included, we should try to finish it off soon...

**Comment by lfos** [comment]
Status?

**Comment by lfos** [comment]
Closing this for now. Please reopen if you decide to complete this...

**Pull request closed without merging**
