### PR TITLE
Treat recurrence item parameters as a unit

### PR DESCRIPTION
**Pull request by lhca**
Adresses GitHub issue #220.

### CODE REVIEW

**Comment by lfos** [comment]
Merged, thanks!

**Comment by lhca** [comment]
Note. Has been updated.

**Comment by lfos** [comment]
I don't see any updates in the branch. What was the problem with the previous attempt?

**Comment by lhca** [comment]
I force-pushed an update (and it is there), but for whatever reason GitHub doesn't say so.

The problem was that the result of recur_update_exc() was not returned and checked. But I have just realized that the also the second attempt is incomplete. Sigh.

**Comment by lhca** [comment]
Third attempt uploaded (force-pushed) as a replacement (not a separate patch).

The problem with the first attempt (still on pu) is that not only the result of `update_exc()`, but also that of  `recur_update_exc()` must be handled. The second attempt did this incorrectly.

**Comment by lhca** [comment]
I have just discovered yet another bug in this error-ridden PR.

If you edit the repetition part of a recurrent item, changes have no effect -- unless the item has an exception date.

A fix is upcoming.

**Pull request closed without merging**
