### PR TITLE
Test for the directory structure

### PR DESCRIPTION
**Pull request by Nitroretro**
Ensure that calcurse uses the right data and configuration directories depending on the conditions.

**Related:** #254 (issue: #252)

### CODE REVIEW

**Comment by lfos** [comment]
Awesome, thank you! Merged into `pu`.

**Comment by Nitroretro** [comment]
No problem!

**Comment by lhca** [comment]
Older Linux installations (mine for example) do not have `realpath`, which causes `io-005.sh` and `io-006.sh` to fail. But `readlink -f` will do.

**Comment by lfos** [comment]
> Older Linux installations (mine for example) do not have `realpath`, which causes `io-005.sh` and `io-006.sh` to fail. But `readlink -f` will do.

Good catch! I updated the patch on `pu`.

**Pull request closed without merging**
