### PR TITLE
Check if the configuration folder exists

### PR DESCRIPTION
**Pull request by hiqua**
Fix an omission in #131.

@lhca can you check that I didn't forget anything this time? Thanks!

### CODE REVIEW

**Comment by lfos** [comment]
We should probably add tests for the new flag. Can be done in a follow-up series, though. Merged into `pu`. Thanks!

**Comment by lhca** [comment]
@hiqua Well, you asked for it! There are also checks for directories in `args.c()` for non-interactive mode.

Maybe @lfos could see to that, and at the same time also fix `path_hooks` which is missing in both interactive and non-interactive mode.

**Comment by hiqua** [comment]
I'll have a look (at least for the `arcs.c()` thing), thanks!

**Comment by lhca** [comment]
There are problems with this patch, and they are not solved by https://github.com/lfos/calcurse/commit/e3ca60eefe08b253ff436fe16d85b4317c7a2523.

It may be a copy-paste typo, but the three original lines

> snprintf(path_conf, BUFSIZ, "%s/" CONF_PATH_NAME, conf_home);
snprintf(path_keys, BUFSIZ, "%s/" KEYS_PATH_NAME, conf_home);
snprintf(path_hooks, BUFSIZ, "%s/" HOOKS_DIR_NAME, conf_home);

works when -C confdir is given, but not when -C is absent.

With the three new lines it is the other way around:

> snprintf(path_conf, BUFSIZ, "%s/" CONF_PATH, conf_home);
snprintf(path_keys, BUFSIZ, "%s/" KEYS_PATH, conf_home);
snprintf(path_hooks, BUFSIZ, "%s/" HOOKS_DIR, conf_home);

The reason is that the macros ending in _PATH and _DIR include `.calcurse/` and are for the default case only, while those ending in _NAME are file names and are for the non-default cases. The use of them must be conditioned by `confdir`.

The `io_init()` routine can only be read with great effort and should be rewritten. There should also be a check on the size of the user supplied directory paths. They are copied into fix-sized buffers. I have attached a suggestion.
[io_init.txt](https://github.com/lfos/calcurse/files/2592263/io_init.txt)

**Comment by lfos** [comment]
True. I'd be happy about the patch. We should avoid using buffer sizes and magic constants, though. And if possbile, we should even avoid snprintf() and use the string_*() functions or asprintf() instead. Thanks!

**Pull request closed without merging**
