### PR TITLE
Feature Request #228: create appointment from task

### PR DESCRIPTION
**Pull request by igordsm**
Implementation of Issue #228, which requests the addition of an option to create Appointments from the TODO panel with the text of the current task as the appointments' description.

### CODE REVIEW

**Comment by igordsm** [comment]
Hey @lfos, could you review this when you have some time? I don't want to put pressure on you or anything, but I've been using this PR for a week and it would be awesome if it was included in the official releases!

**Comment by lfos** [comment]
Of course, thanks for the PR. The patch looks good. The only thing I don't like is using one of the few keys that we have left. If we continue doing this, we will run out of keys at some point and there will be no way back. I think we should switch to vim-like key prefixes for some new (less common commands). For example, we could use `za` to turn a todo into an appointment.

**Comment by igordsm** [comment]
@lfos  thank you! I added a new commit to the PR removing the Z shortcut and adding a commando to key_generic_cmd. If things look good I can squash it to a single commit to make life easier for you. 

Best regards.

**Comment by lfos** [comment]
I was not talking about turning it into a command. Why I suggested is being able to press `z` followed by `a` in normal mode to generate the new item. This allows us to add further key bindings prefixed by `z` later. For example, `zj` could jump to the next appointment in the appointments panel.

**Comment by igordsm** [comment]
Oh, I guess I was confused about the correct naming of thing in calcurse. Sorry about that. You mean like the "C" key for Config ?

**Comment by lfos** [comment]
> Oh, I guess I was confused about the correct naming of thing in calcurse. Sorry about that. You mean like the "C" key for Config ?

Exactly!

**Comment by kevinhwang91** [comment]
@igordsm Adding todo to appt, the description works fine but not the notes.

**Comment by igordsm** [comment]
@kevinhwang91 I have a prototype that also added the note to the appointment.  Unfortunately I have not found a way to link the appointment's note to the original Task's. I can copy it, but changing one does not automatically change the other. 

I've been a bit busy this past week, but I plan to come back to calcurse by the end of this week.

**Comment by lfos** [comment]
Yes, there currently isn't any code that allows to attach the same note to multiple items (and keep the content synced).

A similar idea that has been discuessed multiple times in the past is named notes. Think of it as a symlink-like indirection: an appointment points to a note name and the note name points to the actual note. If you edit the note, it is still available under the original note name and all references to that named note will automatically point to the new note content.

**Comment by lfos** [comment]
What's the status of this? To avoid more bikeshedding, maybe we should simply create a copy of the note for now?

**Comment by lfos** [comment]
Closing for now. Please reopen if you find time to complete this patch set!

**Pull request closed without merging**
