### PR TITLE
Fix recurrent appointment end time when duration is zero

### PR DESCRIPTION
**Pull request by lhca**
Signed-off-by: Lars Henriksen <LarsHenriksen@get2net.dk>

### CODE REVIEW

**Comment by lfos** [comment]
Since this fixes a regression, I think we should mention the commit that introduced the bug in the commit message (for the record). Is it 223810c (Major overhaul of appointment/event input routines., 2017-11-06)?

**Comment by lhca** [comment]
Yes, in combination with 16d3032 (Refactoring update_duration/day_edit_duration, 2017/10/18).

**Comment by lfos** [comment]
As I mentioned in the bug reports, this does not fix #213. Is this PR just an unrelated fix and #213 still needs work?

**Comment by lhca** [comment]
Clearly there is a bug that is fixed. Whether it is unrelated to #213 I don't know, see my comment there.

**Comment by lfos** [comment]
I am quite confused. Your comment in #213 claims that this PR yields the "desired consistency". Does this not refer to the inconsistency mentioned in the original PR?

**Comment by lfos** [comment]
Merged into pu, thanks!

**Pull request closed without merging**
