### PR TITLE
Adds batch add functionality requested in #169

### PR DESCRIPTION
**Pull request by igordsm**
This PR adds an option "Add Batch" (shortcut "b B") that keeps calling "key_add_item" until the addition is cancelled by pressing "ESC". It works for both tasks and appointments/events. Requested in issue #169

### CODE REVIEW

**Comment by igordsm** [comment]
@lfos You mentioned in #229 that we should avoid adding new keys. Do you think we should apply it to this command as well?

**Comment by lfos** [comment]
Are there other operations where a batch mode might make sense? Batch updates, batch removals? If so, we might want to make `b` a prefix key that can be used with other operations.

**Comment by lhca** [comment]
The global flag `modified` in `io.c` mirrors the state of online (in-memory) data as opposed to offline (on-disk) data: 

- when it is unset, in-memory and on-disk data are in agreement.
- when it is set, in-memory data disagree with on-disk data

The flag is unset at start of calcurse and after each successful save operation.

Your patch breaks this mechanism in a threaded application like calcurse which has a periodic save thread.

**Comment by igordsm** [comment]
@lhca I did not realize this! I will update the patch later this week to fix this.

**Comment by igordsm** [comment]
@lhca I refactored the code so that `key_add_item` (and the functions it calls) returns 1 if the element really was added. This avoids using the `modified` flag and makes the rest of the patch trivial.

**Comment by lhca** [comment]
Yes, giving `key_add_item()` a return value seems the obvious and simple answer.

**Comment by igordsm** [comment]
@lhca I squashed both commits. 

@lfos Thinking again, I don't think the suggestion applies here. 

Any other suggestions for improvements?

**Comment by lfos** [comment]
Any updates on this. Did you think about making the batch mode key a prefix key as discussed previously?

**Comment by igordsm** [comment]
Hey @lfos , sorry for the wait.  I initially implemented it using the Add Item command, but it does not allow for different types of adding in the same batch. Do you think adding a batch mode key prefix would be useful? The "next level" of menu would contain the type of the item to add, in this case. 

I am not sure I would use, but am willing to implement it if others think it would be useful.

**Comment by igordsm** [comment]
Hey @lfos , sorry for the wait.  I initially implemented it using the Add Item command, but it does not allow for different types of adding in the same batch. Do you think adding a batch mode key prefix would be useful? The "next level" of menu would contain the type of the item to add, right?

I am not sure I would use, but am willing to implement it if others think it would be useful.

**Comment by lfos** [comment]
Sorry again for the super late reply. We should work on getting this done. I don't think the second level should only allow you to select an item type. We can simply allow for choosing some of the already existing key bindings. As a first step, I'd be fine with only supporting `a` (add item), `^A` (add appointment) and `^T` (add todo item).

**Comment by lfos** [comment]
Closing for now. Please reopen if you find time to complete this patch set!

**Pull request closed without merging**
